#!/usr/bin/env python3
"""Compile selected, current translator variants into a text-only browser catalog."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARAM = re.compile(r'\{([a-zA-Z][a-zA-Z0-9_]*)\}')

def placeholders(message):
    if isinstance(message, str):
        return set(PARAM.findall(message))
    if not isinstance(message, dict) or 'other' not in message or not all(isinstance(v, str) for v in message.values()):
        raise ValueError('Messages must be text or plural forms with an other form')
    if set(message) - {'zero', 'one', 'two', 'few', 'many', 'other'}:
        raise ValueError('Unknown plural category')
    return set().union(*(set(PARAM.findall(v)) for v in message.values()))

def compile_catalog(root=ROOT):
    source = json.loads((root/'locales/en.json').read_text())
    policy = json.loads((root/'locales/selection.json').read_text())
    english = {key: entry['text'] for key, entry in source['messages'].items()}
    for message in english.values(): placeholders(message)
    output = {'schema':1, 'sourceLocale':'en', 'locales':{'en':{'label':'English', 'messages':english}}}
    coverage = {}
    for locale, selection in policy['locales'].items():
        if locale == 'en': raise ValueError('Cannot replace the English source catalog')
        variants = {}
        for path in sorted((root/'locales/variants'/locale).glob('*.json')):
            variant = json.loads(path.read_text())
            if variant['locale'] != locale: raise ValueError(f'Locale mismatch in {path}')
            profile = variant['profile']['id']
            if profile in variants: raise ValueError(f'Duplicate profile {profile}')
            variants[profile] = variant
        defaults = selection['defaultProfile']
        if defaults not in variants: raise ValueError(f'Unknown profile {defaults}')
        overrides = selection.get('overrides', {})
        if set(overrides) - set(english): raise ValueError('Unknown source key in selection overrides')
        messages, provenance, gaps = {}, {}, {}
        for key, original in english.items():
            profile = overrides.get(key, defaults)
            if profile not in variants: raise ValueError(f'Unknown profile {profile}')
            entry = variants[profile]['messages'].get(key)
            if not entry:
                gaps[key] = 'missing'; continue
            if entry.get('source') != original:
                gaps[key] = 'stale'; continue
            translated = entry['text']
            if isinstance(original, str) != isinstance(translated, str): raise ValueError(f'{key}: message type changed')
            if placeholders(original) != placeholders(translated): raise ValueError(f'{key}: placeholders changed')
            # Require all source placeholders in every target plural form too.
            if isinstance(translated, dict) and any(set(PARAM.findall(v)) != placeholders(original) for v in translated.values()):
                raise ValueError(f'{key}: incomplete plural form')
            messages[key] = translated
            provenance[key] = {'profile':profile, 'sourceSha256':hashlib.sha256(json.dumps(original,ensure_ascii=False,sort_keys=True).encode()).hexdigest()}
        output['locales'][locale] = {'label':selection['label'], 'messages':messages, 'provenance':provenance}
        coverage[locale] = {'translated':len(messages), 'total':len(english), 'fallbacks':gaps}
    return output, coverage

def javascript(catalog):
    # Safe both as a standalone script and if a downstream build embeds it.
    payload = json.dumps(catalog, ensure_ascii=False, sort_keys=True, indent=2).replace('<', '\\u003c').replace('\u2028','\\u2028').replace('\u2029','\\u2029')
    return '/* Generated by tools/build-ui-catalog.py; edit locales/, not this file. */\nwindow.UW_UI_CATALOG = '+payload+';\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the checked-in browser catalog is out of date')
    args = parser.parse_args()
    catalog, coverage = compile_catalog()
    target = ROOT/'dashboard/static/i18n-catalog.js'
    content = javascript(catalog)
    if args.check:
        if not target.exists() or target.read_text() != content: raise SystemExit('Run tools/build-ui-catalog.py to refresh the browser catalog')
    else:
        target.write_text(content)
    print(json.dumps(coverage, ensure_ascii=False, indent=2))
